name: Deploy Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.SAMDEPLOYERROLEARN }}
    - name: Install Dotnet-Lambda tool
      run: dotnet tool install --global Amazon.Lambda.Tools
    - name: Deploy
      run: dotnet lambda deploy-serverless --stack-name LeetcodeDailyChallengeLambda --s3-bucket leetcode-daily-challenge-store --template src/LeetcodeDailyChallengeReminder/serverless.template --region eu-west-1 --framework net9.0
